apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTmRVSXBsRmNzVFF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpBNE1qWXhOVFF4TURkYUZ3MHpNekE0TWpNeE5UUXhNRGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURBdEI3ZkxSTHQvejJ4QWtLajdxWXJmWUhzY2M2bUZMdnlsT1hJaG1wZXUzKzZod1pzWEc4Q2pGMEoKNzhDd3FVOWExYVJLcVhVTDZoN2E0Wk52a0Juc3A4cjlGUVFSdk5RYkdxQWk5djUrbzE5eUVDQXRUQ1hPb1Z1NQpXazg3NFZLYkRsRStRRXRMTDhEaTV2RUlJdU1JVzVsNlJ5c0FqZS9uOGErSmtMUG44NkdMY3ppdmdESjFQQ1FuCldvYmZDcWVCdm1OZ0dlQ1IyVlRGSktrQXdIbDY3Uk5Hb3BCelRIWEpNUTR2VEtQa29weG1CMXBpQTYzczVRRUQKN2N2UXFyMEIwSUMzQzFqMGUwSTdaTjRHMnl3c1liTkllTy9SNzlEOG53S3dOeE83Y3c2UU9hUFFEQ1ZrUG45aQoxRmpmZmFXTHcxcW13QW1wVldCUXRDb3hTMWVMQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUenlkL2RZdmluNWZqTVV1dCt6aG1iTEFQMm1EQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjdFbDZXOXhKNAp0MTFDemhKaWh4WTBZNVBCUVFqLytKYXNlMXNWSENzZ2tCVXdVNldkUDdDV05yazVqS2l0QjdZZ0p2TTN2cFY3CnFTejZRYWNsUlFqcnBOZlJkN2dWZDQyVjdRYmxFNTdDSTNjNmc3Ukt4aHJ0RDNXK3YvTUJVS2pKeFQ5ejBLMmEKN0dGWlM0Q2NiMnNDdGZEWVpIa1J4RXlHQ2UxSEN5c01QNDJmbzNCM1NSbkdUSS8xbkFqSE0zUjNUdmhwZnAwTQpUOHpzUS83K1Avc2dTeXlNbTBIbHp2YnRUM01xTTJUd21VSkNCMCtHTEljTVJFMmFIMG9Sa1N4VFBXdlZHMENsCko3M2x3YVZ5YkZ2RFk2bmFhSTcrR3F0L2ZRUnFFbVZEMnovSFp0TUV5bE94N0dQOGJ3Y1M2bkVVYUVpYTB2MWcKN055Sk9uUnhWbUErCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://A535425DA773355B212EBEBD5A50F3DE.gr7.eu-central-1.eks.amazonaws.com
  name: eks-main
contexts:
- context:
    cluster: eks-main
    namespace: kube-system
    user: aws
  name: aws
current-context: aws
kind: Config
preferences:
  colors: true
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - eks-main
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
