---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  labels:
    app: nginx
  name: nginx-provisioner
spec:
  consolidation:
    enabled: true
  labels:
    karpenter: enabled
    app: nginx
  taints: []
  providerRef:
    name: bottlerocket
  requirements:
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
      - t
  - key: karpenter.k8s.aws/instance-cpu
    operator: In
    values:
    - "2"
  - key: karpenter.k8s.aws/instance-memory
    operator: In
    values:
    - "2048"
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
