---
apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  namespace: btc
  labels:
    app: bitcoind
spec:
  ports:
  - name: rpc
    port: 8333
    protocol: TCP
    targetPort: 8333
  - name: zmq
    port: 8332
    protocol: TCP
    targetPort: 8332
  selector:
    app: bitcoin-node
  type: ClusterIP
